version: '3.8'
services:
  app:
    build: .
    ports:
      - '80'  # Mapeia a porta 80 do host para a porta 3000 do container
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
