#version: '3.8'

services:
  app-backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "npm run seed:run &&
             npm run dev"
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      GEMINI_KEY: ${GEMINI_KEY}
    restart: always
  db:
    container_name: api-teste-database
    image: mysql
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  app-frontend:
    build:
      context: ../front-end/
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/front-end:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm run dev"
    restart: always

